language: python
sudo: required
services:
  - docker

addons:
  ssh_known_hosts: 37.139.22.109

script:
  - docker build -t dokku/clippy:latest .

before_install:
  - openssl aes-256-cbc -K $encrypted_4ed4cdc9df6d_key -iv $encrypted_4ed4cdc9df6d_iv -in etc/deploy_key.enc -out etc/deploy_key -d

after_success:
- |
    #!/bin/bash
    set -e

    # start ssh agent

    if [ "$TRAVIS_PULL_REQUEST" == "false" ] &&
       [ "$TRAVIS_REPO_SLUG" == "gnunicorn/clippy-service" ] &&
       [ "$TRAVIS_BRANCH" == "master" ]; then
      eval "$(ssh-agent -s)"
      chmod 600 etc/deploy_key
      ssh-add etc/deploy_key

      docker save dokku/clippy:latest | bzip2 | ssh root@37.139.22.109 "bunzip2 | docker load"
      ssh root@37.139.22.109 "dokku tags:deploy clippy"

    else
      echo "Not deploying"
    fi
